import type { CollectionConfig } from "payload"
import { siteScopedRead } from '../access/siteScopedRead'

export const Wines: CollectionConfig = {
  slug: "wines",
  admin: {
    useAsTitle: "name",
    defaultColumns: ["name", "winery", "varietal", "vintage"],
    group: "Wine Country Corner",
  },
  access: { read: siteScopedRead },
  fields: [
    {
      name: "site",
      type: "relationship",
      relationTo: "sites",
      required: true,
      admin: { position: "sidebar" },
    },
    { name: "name", type: "text", required: true },
    { name: "slug", type: "text", required: true, unique: true, admin: { position: "sidebar" } },
    {
      name: "winery",
      type: "relationship",
      relationTo: "wineries",
    },
    {
      name: "shortName",
      type: "text",
      label: "Short Name",
      admin: { description: "Compact label for cards and nav, e.g. \"Cabernet 2019\"." },
    },
    { name: "varietal", type: "text" },
    { name: "vintage", type: "number" },
    { name: "ava", type: "text", label: "AVA", admin: { description: "American Viticultural Area." } },
    { name: "blend", type: "text", admin: { description: "Composition, e.g. \"92% Cabernet, 8% Merlot\"." } },
    { name: "aging", type: "textarea" },
    { name: "abv", type: "number", label: "ABV %" },
    { name: "description", type: "textarea" },
    { name: "tastingNotes", type: "textarea", label: "Tasting Notes" },
    { name: "drinkWindow", type: "text", label: "Drink Window", admin: { description: "e.g. \"2026–2038\"." } },
    {
      name: "pairings",
      type: "array",
      fields: [{ name: "pairing", type: "text", required: true }],
    },
    { name: "price", type: "number" },
    { name: "priceNote", type: "text", label: "Price Note", admin: { description: "Qualifier shown beside the price, e.g. \"per 3-bottle set\"." } },
    { name: "cases", type: "number", admin: { description: "Cases produced." } },
    {
      name: "points",
      type: "number",
      admin: { description: "Critic score, e.g. 95. Use this rather than Rating." },
    },
    { name: "pointsSource", type: "text", label: "Points Source", admin: { description: "Who scored it, e.g. \"Wine Enthusiast\"." } },
    { name: "pointsQuote", type: "textarea", label: "Points Quote" },
    {
      name: "priceTier",
      type: "select",
      label: "Price Tier",
      options: [
        { label: "Under $50", value: "under-50" },
        { label: "$50–$100", value: "50-100" },
        { label: "$100–$200", value: "100-200" },
        { label: "Over $200", value: "over-200" },
      ],
    },
    { name: "rating", type: "number" },
    { name: "purchaseUrl", type: "text", label: "Purchase URL" },
    { name: "ctaLabel", type: "text", label: "CTA Label", admin: { description: "Button text for the purchase link, e.g. \"Join the list\"." } },
    { name: "image", type: "upload", relationTo: "media" },
    {
      name: "imageUrl",
      type: "text",
      label: "Image URL",
      admin: { description: "Fallback bottle image URL for wines without an uploaded media object." },
    },
    { name: "featured", type: "checkbox", defaultValue: false, admin: { position: "sidebar" } },
    { name: "memberOnly", type: "checkbox", label: "Member Only", defaultValue: false, admin: { position: "sidebar" } },
    { name: "soldOut", type: "checkbox", label: "Sold Out", defaultValue: false, admin: { position: "sidebar" } },
  ],
  timestamps: true,
}
