#!/usr/bin/env bash
# sync-payload-cms-hosts.sh — sync the traefik-prod file-provider route for Payload CMS
# from the payload DB's sites_domains table.
#
# Topology (standalone, post-swarm-exit):
#   - payload-app runs standalone on xenco0 (10.8.8.10:3000), NO traefik labels
#   - traefik-prod runs on xenco7; its dynamic dir is bind-mounted on the host at
#     /home/xen/traefik-prod/dynamic (-> /etc/traefik/dynamic in the container)
#   - the file provider watches that dir, so writes hot-reload with no restart
#
# Host generation rule (matches the hand-maintained file as of 2026-08-15):
#   every distinct apex in sites_domains (www./cms. prefixes stripped) gets a
#   cms.<apex> host, unioned with STATIC_EXTRA_HOSTS below.
#   Apex/www domains themselves are NOT routed here — they point at the site
#   frontends (Vercel), not at Payload.
#
# Replaces the swarm-era scripts/sync-traefik-domains.sh, which built
# docker-stack labels and no longer matches this topology.
#
# Usage:
#   ./scripts/sync-payload-cms-hosts.sh                    # dry run: show diff only
#   ./scripts/sync-payload-cms-hosts.sh --apply            # back up + write + verify
#   ./scripts/sync-payload-cms-hosts.sh --apply --allow-removals
#
# Removals are refused without --allow-removals: a bad DB query result must not
# be able to silently drop live CMS hosts.

set -euo pipefail

DB_SSH="xenco0.xenco.lan"
DB_CONTAINER="payload-postgres"
DB_USER="payload"
DB_NAME="payload"

TRAEFIK_SSH="xenco7.xenco.lan"
TRAEFIK_FILE="/home/xen/traefik-prod/dynamic/payload-cms.yml"

BACKEND_URL="http://10.8.8.10:3000"
HEALTH_PATH="/api/support/uptime"
SENTINEL_HOST="cms.xencolabs.com"

# Hosts routed to Payload that are not derivable from sites_domains.
STATIC_EXTRA_HOSTS=(
  "publish.xencolabs.com"
)

APPLY=0
ALLOW_REMOVALS=0
for arg in "$@"; do
  case "$arg" in
    --apply) APPLY=1 ;;
    --allow-removals) ALLOW_REMOVALS=1 ;;
    -h|--help) grep '^#' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "unknown arg: $arg (try --help)" >&2; exit 2 ;;
  esac
done

SSH=(ssh -o BatchMode=yes)

GENERATED=$(mktemp) LIVE=$(mktemp)
trap 'rm -f "$GENERATED" "$LIVE"' EXIT

echo "==> Reading sites_domains from ${DB_CONTAINER} on ${DB_SSH}"
domains=$("${SSH[@]}" "$DB_SSH" \
  "docker exec $DB_CONTAINER psql -U $DB_USER -d $DB_NAME -Atc 'SELECT DISTINCT domain FROM sites_domains'")

if [[ -z "$domains" ]]; then
  echo "ERROR: sites_domains query returned nothing — refusing to generate an empty route." >&2
  exit 1
fi

mapfile -t hosts < <(
  {
    while IFS= read -r d; do
      apex="${d#www.}"
      apex="${apex#cms.}"
      echo "cms.${apex}"
    done <<<"$domains"
    printf '%s\n' "${STATIC_EXTRA_HOSTS[@]}"
  } | sort -u
)

count=${#hosts[@]}
if (( count < 10 )); then
  echo "ERROR: only ${count} hosts generated — below sanity floor of 10. Aborting." >&2
  exit 1
fi

rule=$(printf 'Host(`%s`) || ' "${hosts[@]}")
rule="${rule% || }"

cat >"$GENERATED" <<EOF
# Payload CMS — ${count}-host file-provider route on traefik-prod (xenco7)
# Backend: standalone payload-app on xenco0 (${BACKEND_URL})
# GENERATED by payload-swarm/scripts/sync-payload-cms-hosts.sh — do not hand-edit.
# To add a host: add the domain to the site in Payload (sites_domains), or to
# STATIC_EXTRA_HOSTS in the script, then re-run with --apply.
http:
  routers:
    payload-cms:
      rule: "${rule}"
      entryPoints:
        - websecure
      service: payload-cms
      tls:
        certResolver: cf
  services:
    payload-cms:
      loadBalancer:
        servers:
          - url: "${BACKEND_URL}"
        passHostHeader: true
        healthCheck:
          path: ${HEALTH_PATH}
          interval: 30s
          timeout: 10s
EOF

echo "==> Fetching live config from ${TRAEFIK_SSH}:${TRAEFIK_FILE}"
"${SSH[@]}" "$TRAEFIK_SSH" "cat $TRAEFIK_FILE" >"$LIVE" 2>/dev/null \
  || echo "WARN: live file missing or unreadable — treating as empty."

live_hosts=$(grep -o 'Host(`[^`]*`)' "$LIVE" | sed 's/Host(`//;s/`)//' | sort -u || true)
new_hosts=$(printf '%s\n' "${hosts[@]}")

added=$(comm -13 <(printf '%s\n' "$live_hosts") <(printf '%s\n' "$new_hosts") | grep -v '^$' || true)
removed=$(comm -23 <(printf '%s\n' "$live_hosts") <(printf '%s\n' "$new_hosts") | grep -v '^$' || true)

if [[ -z "$added" && -z "$removed" ]]; then
  echo "In sync: ${count} hosts, no changes needed."
  exit 0
fi

[[ -n "$added" ]]   && { echo "Hosts to ADD:";    sed 's/^/  + /' <<<"$added"; }
[[ -n "$removed" ]] && { echo "Hosts to REMOVE:"; sed 's/^/  - /' <<<"$removed"; }

if [[ -n "$removed" && "$ALLOW_REMOVALS" -ne 1 ]]; then
  echo "ERROR: removals detected but --allow-removals not set." >&2
  echo "A DB glitch must not take live CMS hosts down. Re-run with --allow-removals if intentional." >&2
  exit 1
fi

if (( APPLY != 1 )); then
  echo
  echo "Dry run — nothing written. Re-run with --apply."
  exit 0
fi

ts=$(date +%Y%m%d-%H%M%S)
echo "==> Backing up live config to ${TRAEFIK_FILE}.bak-${ts}"
"${SSH[@]}" "$TRAEFIK_SSH" "cp $TRAEFIK_FILE ${TRAEFIK_FILE}.bak-${ts}" 2>/dev/null \
  || echo "WARN: no live file to back up."

echo "==> Writing new config (atomic mv; file provider hot-reloads)"
scp -o BatchMode=yes -q "$GENERATED" "${TRAEFIK_SSH}:${TRAEFIK_FILE}.tmp"
"${SSH[@]}" "$TRAEFIK_SSH" "mv ${TRAEFIK_FILE}.tmp $TRAEFIK_FILE"

echo "==> Verifying (new hosts may 404/526 until Cloudflare DNS + cert exist)"
sleep 5
for h in $added; do
  code=$(curl -s -o /dev/null -m 15 -w '%{http_code}' "https://${h}/" || echo "ERR")
  echo "   https://${h}/ -> ${code}"
done
code=$(curl -s -o /dev/null -m 15 -w '%{http_code}' "https://${SENTINEL_HOST}/" || echo "ERR")
echo "   sentinel https://${SENTINEL_HOST}/ -> ${code}"
if [[ "$code" != "200" ]]; then
  echo "ERROR: sentinel host is not 200 — roll back with:" >&2
  echo "  ssh ${TRAEFIK_SSH} 'cp ${TRAEFIK_FILE}.bak-${ts} ${TRAEFIK_FILE}'" >&2
  exit 1
fi
echo "Done: ${count} hosts live."
