/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    sites: Site;
    articles: Article;
    authors: Author;
    categories: Category;
    tags: Tag;
    support_kb_articles: SupportKbArticle;
    support_playbooks: SupportPlaybook;
    support_announcements: SupportAnnouncement;
    internal_link_rules: InternalLinkRule;
    internal_link_edges: InternalLinkEdge;
    internal_link_runs: InternalLinkRun;
    suites: Suite;
    reviews: Review;
    'directory-entries': DirectoryEntry;
    events: Event;
    wineries: Winery;
    wines: Wine;
    restaurants: Restaurant;
    accommodations: Accommodation;
    'winery-events': WineryEvent;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    sites: SitesSelect<false> | SitesSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    support_kb_articles: SupportKbArticlesSelect<false> | SupportKbArticlesSelect<true>;
    support_playbooks: SupportPlaybooksSelect<false> | SupportPlaybooksSelect<true>;
    support_announcements: SupportAnnouncementsSelect<false> | SupportAnnouncementsSelect<true>;
    internal_link_rules: InternalLinkRulesSelect<false> | InternalLinkRulesSelect<true>;
    internal_link_edges: InternalLinkEdgesSelect<false> | InternalLinkEdgesSelect<true>;
    internal_link_runs: InternalLinkRunsSelect<false> | InternalLinkRunsSelect<true>;
    suites: SuitesSelect<false> | SuitesSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    'directory-entries': DirectoryEntriesSelect<false> | DirectoryEntriesSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    wineries: WineriesSelect<false> | WineriesSelect<true>;
    wines: WinesSelect<false> | WinesSelect<true>;
    restaurants: RestaurantsSelect<false> | RestaurantsSelect<true>;
    accommodations: AccommodationsSelect<false> | AccommodationsSelect<true>;
    'winery-events': WineryEventsSelect<false> | WineryEventsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  site?: (number | null) | Site;
  alt: string;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sites".
 */
export interface Site {
  id: number;
  name: string;
  slug: string;
  /**
   * Domains that should resolve to this site (e.g. fightclubtech.com). Do NOT include protocol.
   */
  domains?:
    | {
        domain: string;
        id?: string | null;
      }[]
    | null;
  isDefault?: boolean | null;
  /**
   * Full URL for on-demand revalidation (e.g., https://resumecoach.me/api/revalidate). Leave empty to skip.
   */
  revalidateUrl?: string | null;
  /**
   * Secret token for the revalidation endpoint (passed as ?secret=...)
   */
  revalidateSecret?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  slug: string;
  /**
   * Short summary used on listing pages / previews.
   */
  excerpt?: string | null;
  /**
   * Main image for article cards and social sharing (recommended: 1200x630)
   */
  featuredImage?: (number | null) | Media;
  /**
   * Optional hero background image (full-width, can be same as featured)
   */
  heroImage?: (number | null) | Media;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Raw HTML from WordPress import. Rendered when Lexical content is not available.
   */
  html?: string | null;
  /**
   * First image extracted from imported HTML. Used for article cards.
   */
  thumbnailUrl?: string | null;
  categories?: (number | Category)[] | null;
  tags?: (number | Tag)[] | null;
  author?: (number | null) | Author;
  site: number | Site;
  status: 'draft' | 'published';
  publishedAt?: string | null;
  /**
   * Custom page <title> for search engines (50-60 chars). Falls back to title + site name.
   */
  metaTitle?: string | null;
  /**
   * Custom meta description for search results (150-160 chars). Falls back to excerpt.
   */
  metaDescription?: string | null;
  /**
   * Primary keyword this article targets. Used by SEO scoring and frontend optimization.
   */
  focusKeyword?: string | null;
  /**
   * Custom canonical URL if this article is syndicated or republished from another source.
   */
  canonicalUrl?: string | null;
  /**
   * Prevent search engines from indexing this article.
   */
  noIndex?: boolean | null;
  /**
   * Optional custom JSON-LD override. Leave empty to auto-generate Article schema.
   */
  structuredData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Latest SEO score (0–100).
   */
  seoScore?: number | null;
  seoGrade?: string | null;
  seoScoredAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  slug: string;
  description?: string | null;
  /**
   * Select parent category for hierarchy
   */
  parent?: (number | null) | Category;
  site: number | Site;
  breadcrumbs?:
    | {
        doc?: (number | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  name: string;
  slug: string;
  site: number | Site;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  name: string;
  slug: string;
  bio?: string | null;
  avatar?: (number | null) | Media;
  /**
   * External image URL (e.g. from R2/Blogcraft). Used when no uploaded avatar is set.
   */
  avatarUrl?: string | null;
  website?: string | null;
  site: number | Site;
  isDefault?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "support_kb_articles".
 */
export interface SupportKbArticle {
  id: number;
  /**
   * App identifier (e.g., "chat-widget", "dashboard")
   */
  appSlug: string;
  title: string;
  /**
   * Brief description shown in search results
   */
  summary?: string | null;
  /**
   * URL routes where this article is relevant
   */
  routes?:
    | {
        route: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Numbered steps (e.g., "1. Click Upload 2. Select file...")
   */
  stepsText?: string | null;
  /**
   * Keyword soup: synonyms, common phrasing, error messages
   */
  triggersText?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "support_playbooks".
 */
export interface SupportPlaybook {
  id: number;
  /**
   * App identifier (e.g., "chat-widget", "dashboard")
   */
  appSlug: string;
  title: string;
  /**
   * Brief description of what this playbook handles
   */
  summary?: string | null;
  /**
   * Priority level for this playbook
   */
  severity?: ('low' | 'medium' | 'high' | 'critical') | null;
  /**
   * URL routes where this playbook is relevant
   */
  routes?:
    | {
        route: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Keywords/phrases that trigger this playbook
   */
  triggers?:
    | {
        phrase: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Step-by-step instructions for handling this scenario
   */
  steps: {
    /**
     * Brief title for this step
     */
    stepTitle: string;
    /**
     * Detailed instructions for this step
     */
    stepBody: string;
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "support_announcements".
 */
export interface SupportAnnouncement {
  id: number;
  /**
   * App identifier (e.g., "chat-widget", "dashboard", or "*" for all)
   */
  appSlug: string;
  title: string;
  /**
   * The announcement message (shown in search results as summary)
   */
  message: string;
  /**
   * Severity level for visual styling
   */
  severity?: ('info' | 'warning' | 'critical') | null;
  /**
   * URL routes where this announcement should appear
   */
  routes?:
    | {
        route: string;
        id?: string | null;
      }[]
    | null;
  /**
   * When this announcement becomes active
   */
  startsAt?: string | null;
  /**
   * When this announcement should no longer appear
   */
  expiresAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "internal_link_rules".
 */
export interface InternalLinkRule {
  id: number;
  site: number | Site;
  targetArticle: number | Article;
  keywords: {
    keyword: string;
    id?: string | null;
  }[];
  priority?: number | null;
  maxLinksPerSource?: number | null;
  caseSensitive?: boolean | null;
  partialMatch?: boolean | null;
  enabled?: boolean | null;
  source: 'manual' | 'generated';
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "internal_link_edges".
 */
export interface InternalLinkEdge {
  id: number;
  site: number | Site;
  sourceArticle: number | Article;
  targetArticle: number | Article;
  keywordUsed?: string | null;
  anchorText?: string | null;
  contextHash: string;
  placement: 'in_body' | 'related_reading';
  targetUrl?: string | null;
  leftContext?: string | null;
  rightContext?: string | null;
  fingerprint?: string | null;
  status: 'active' | 'stale' | 'reverted';
  runId: number | InternalLinkRun;
  lastSeenRunId?: (number | null) | InternalLinkRun;
  revertRunId?: (number | null) | InternalLinkRun;
  updatedAt: string;
  createdAt: string;
}
/**
 * Run internal linker manually via endpoint: POST /api/internal-links/run?mode=dry_run|apply&site=all|<id>
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "internal_link_runs".
 */
export interface InternalLinkRun {
  id: number;
  site?: (number | null) | Site;
  mode: 'dry_run' | 'apply';
  status: 'queued' | 'running' | 'succeeded' | 'failed' | 'partial' | 'reverted';
  action: 'link' | 'revert';
  strategyVersion: string;
  trigger: 'manual' | 'scheduled' | 'endpoint';
  startedAt?: string | null;
  endedAt?: string | null;
  cursor?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  stats:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  errors?:
    | {
        articleId?: string | null;
        message: string;
        id?: string | null;
      }[]
    | null;
  lockKey: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "suites".
 */
export interface Suite {
  id: number;
  site: number | Site;
  name: string;
  slug: string;
  tagline: string;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  shortDescription?: string | null;
  details: {
    bedrooms: number;
    bathrooms: number;
    maxGuests: number;
    sqft?: number | null;
    floor?: ('ground' | 'upper') | null;
    hasPatio?: boolean | null;
    hasEnSuite?: boolean | null;
    isADACompliant?: boolean | null;
  };
  amenities?:
    | {
        name: string;
        icon?: string | null;
        id?: string | null;
      }[]
    | null;
  images?:
    | {
        image: number | Media;
        alt: string;
        caption?: string | null;
        isPrimary?: boolean | null;
        id?: string | null;
      }[]
    | null;
  lodgifyPropertyId: string;
  pricing?: {
    baseNightlyRate?: number | null;
    cleaningFee?: number | null;
    directBookingDiscount?: number | null;
  };
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  status?: ('active' | 'inactive') | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  site: number | Site;
  reviewerName: string;
  reviewerLocation?: string | null;
  suite: number | Suite;
  rating: number;
  title?: string | null;
  content: string;
  date: string;
  highlights?:
    | {
        item?: string | null;
        id?: string | null;
      }[]
    | null;
  source?: ('airbnb' | 'vrbo' | 'booking' | 'direct' | 'google') | null;
  isFeatured?: boolean | null;
  status?: ('active' | 'hidden') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "directory-entries".
 */
export interface DirectoryEntry {
  id: number;
  site: number | Site;
  name: string;
  slug: string;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  shortDescription?: string | null;
  category: 'wineries' | 'restaurants' | 'activities' | 'venues';
  subcategory?: string | null;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  featuredImage?: (number | null) | Media;
  logo?: (number | null) | Media;
  location?: {
    address?: string | null;
    city?: string | null;
    latitude?: number | null;
    longitude?: number | null;
    distanceFromProperty?: string | null;
    driveTimeMinutes?: number | null;
  };
  contact?: {
    website?: string | null;
    phone?: string | null;
    email?: string | null;
  };
  details?: {
    priceRange?: ('$' | '$$' | '$$$' | '$$$$') | null;
    hours?: string | null;
    reservationRequired?: boolean | null;
    tastingFeeRange?: string | null;
    cuisineType?: string | null;
    capacity?: string | null;
  };
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
  };
  isFeatured?: boolean | null;
  sortOrder?: number | null;
  status?: ('published' | 'active' | 'inactive') | null;
  sourceUrl?: string | null;
  lastCrawledAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  site: number | Site;
  name: string;
  slug: string;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  shortDescription?: string | null;
  featuredImage?: (number | null) | Media;
  startDate: string;
  endDate?: string | null;
  category?: ('music' | 'wine-food' | 'arts-culture' | 'seasonal' | 'community' | 'festivals') | null;
  location?: {
    venueName?: string | null;
    address?: string | null;
    city?: string | null;
  };
  externalUrl?: string | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
  };
  isFeatured?: boolean | null;
  status?: ('active' | 'past') | null;
  sourceUrl?: string | null;
  lastCrawledAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wineries".
 */
export interface Winery {
  id: number;
  site: number | Site;
  name: string;
  slug: string;
  website?: string | null;
  region?: ('Napa Valley' | 'Sonoma County' | 'Coombsville AVA' | 'Stags Leap District' | 'Other') | null;
  subAppellation?: string | null;
  varietalFocus?:
    | {
        varietal?: string | null;
        id?: string | null;
      }[]
    | null;
  tastingAvailable?: boolean | null;
  tastingBookingUrl?: string | null;
  wineClubEnabled?: boolean | null;
  featured?: boolean | null;
  featuredTier?: ('flagship' | 'featured' | 'listed') | null;
  featuredOrder?: number | null;
  featuredHero?: (number | null) | Media;
  featuredStory?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  featuredQuote?: string | null;
  featuredQuoteAttribution?: string | null;
  phone?: string | null;
  email?: string | null;
  instagramHandle?: string | null;
  address?: {
    street?: string | null;
    city?: string | null;
    state?: string | null;
    zip?: string | null;
  };
  coordinates?: {
    lat?: number | null;
    lng?: number | null;
  };
  partnerSince?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wines".
 */
export interface Wine {
  id: number;
  site: number | Site;
  name: string;
  slug: string;
  winery?: (number | null) | Winery;
  varietal?: string | null;
  vintage?: number | null;
  tastingNotes?: string | null;
  price?: number | null;
  priceTier?: ('under-50' | '50-100' | '100-200' | 'over-200') | null;
  rating?: number | null;
  purchaseUrl?: string | null;
  image?: (number | null) | Media;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "restaurants".
 */
export interface Restaurant {
  id: number;
  site: number | Site;
  name: string;
  slug: string;
  website?: string | null;
  region?: ('Napa Valley' | 'Sonoma County' | 'Other') | null;
  city?: string | null;
  cuisineType?:
    | {
        cuisine?: string | null;
        id?: string | null;
      }[]
    | null;
  priceRange?: ('$' | '$$' | '$$$' | '$$$$') | null;
  wineFocused?: boolean | null;
  reservationsUrl?: string | null;
  address?: {
    street?: string | null;
    city?: string | null;
    state?: string | null;
    zip?: string | null;
  };
  phone?: string | null;
  hours?: string | null;
  featuredImage?: (number | null) | Media;
  featured?: boolean | null;
  featuredTier?: ('flagship' | 'featured' | 'listed') | null;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accommodations".
 */
export interface Accommodation {
  id: number;
  site: number | Site;
  name: string;
  slug: string;
  website?: string | null;
  region?: ('Napa Valley' | 'Sonoma County' | 'Other') | null;
  city?: string | null;
  type?: ('hotel' | 'bb' | 'vacation-rental' | 'resort' | 'inn') | null;
  priceRange?: ('$' | '$$' | '$$$' | '$$$$') | null;
  bookingUrl?: string | null;
  address?: {
    street?: string | null;
    city?: string | null;
    state?: string | null;
    zip?: string | null;
  };
  phone?: string | null;
  amenities?:
    | {
        amenity?: string | null;
        id?: string | null;
      }[]
    | null;
  featuredImage?: (number | null) | Media;
  featured?: boolean | null;
  featuredTier?: ('flagship' | 'featured' | 'listed') | null;
  description?: string | null;
  /**
   * Check for Sonoma Grove Suites — appears first in listings.
   */
  isOwned?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "winery-events".
 */
export interface WineryEvent {
  id: number;
  site: number | Site;
  title: string;
  slug: string;
  winery?: (number | null) | Winery;
  eventType?: ('tasting' | 'dinner' | 'harvest' | 'release' | 'club' | 'other') | null;
  startDate: string;
  endDate?: string | null;
  price?: number | null;
  priceFree?: boolean | null;
  registrationUrl?: string | null;
  description?: string | null;
  featuredImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'sites';
        value: number | Site;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'support_kb_articles';
        value: number | SupportKbArticle;
      } | null)
    | ({
        relationTo: 'support_playbooks';
        value: number | SupportPlaybook;
      } | null)
    | ({
        relationTo: 'support_announcements';
        value: number | SupportAnnouncement;
      } | null)
    | ({
        relationTo: 'internal_link_rules';
        value: number | InternalLinkRule;
      } | null)
    | ({
        relationTo: 'internal_link_edges';
        value: number | InternalLinkEdge;
      } | null)
    | ({
        relationTo: 'internal_link_runs';
        value: number | InternalLinkRun;
      } | null)
    | ({
        relationTo: 'suites';
        value: number | Suite;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'directory-entries';
        value: number | DirectoryEntry;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'wineries';
        value: number | Winery;
      } | null)
    | ({
        relationTo: 'wines';
        value: number | Wine;
      } | null)
    | ({
        relationTo: 'restaurants';
        value: number | Restaurant;
      } | null)
    | ({
        relationTo: 'accommodations';
        value: number | Accommodation;
      } | null)
    | ({
        relationTo: 'winery-events';
        value: number | WineryEvent;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  site?: T;
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sites_select".
 */
export interface SitesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  domains?:
    | T
    | {
        domain?: T;
        id?: T;
      };
  isDefault?: T;
  revalidateUrl?: T;
  revalidateSecret?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  featuredImage?: T;
  heroImage?: T;
  content?: T;
  html?: T;
  thumbnailUrl?: T;
  categories?: T;
  tags?: T;
  author?: T;
  site?: T;
  status?: T;
  publishedAt?: T;
  metaTitle?: T;
  metaDescription?: T;
  focusKeyword?: T;
  canonicalUrl?: T;
  noIndex?: T;
  structuredData?: T;
  seoScore?: T;
  seoGrade?: T;
  seoScoredAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  bio?: T;
  avatar?: T;
  avatarUrl?: T;
  website?: T;
  site?: T;
  isDefault?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  parent?: T;
  site?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  site?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "support_kb_articles_select".
 */
export interface SupportKbArticlesSelect<T extends boolean = true> {
  appSlug?: T;
  title?: T;
  summary?: T;
  routes?:
    | T
    | {
        route?: T;
        id?: T;
      };
  stepsText?: T;
  triggersText?: T;
  body?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "support_playbooks_select".
 */
export interface SupportPlaybooksSelect<T extends boolean = true> {
  appSlug?: T;
  title?: T;
  summary?: T;
  severity?: T;
  routes?:
    | T
    | {
        route?: T;
        id?: T;
      };
  triggers?:
    | T
    | {
        phrase?: T;
        id?: T;
      };
  steps?:
    | T
    | {
        stepTitle?: T;
        stepBody?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "support_announcements_select".
 */
export interface SupportAnnouncementsSelect<T extends boolean = true> {
  appSlug?: T;
  title?: T;
  message?: T;
  severity?: T;
  routes?:
    | T
    | {
        route?: T;
        id?: T;
      };
  startsAt?: T;
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "internal_link_rules_select".
 */
export interface InternalLinkRulesSelect<T extends boolean = true> {
  site?: T;
  targetArticle?: T;
  keywords?:
    | T
    | {
        keyword?: T;
        id?: T;
      };
  priority?: T;
  maxLinksPerSource?: T;
  caseSensitive?: T;
  partialMatch?: T;
  enabled?: T;
  source?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "internal_link_edges_select".
 */
export interface InternalLinkEdgesSelect<T extends boolean = true> {
  site?: T;
  sourceArticle?: T;
  targetArticle?: T;
  keywordUsed?: T;
  anchorText?: T;
  contextHash?: T;
  placement?: T;
  targetUrl?: T;
  leftContext?: T;
  rightContext?: T;
  fingerprint?: T;
  status?: T;
  runId?: T;
  lastSeenRunId?: T;
  revertRunId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "internal_link_runs_select".
 */
export interface InternalLinkRunsSelect<T extends boolean = true> {
  site?: T;
  mode?: T;
  status?: T;
  action?: T;
  strategyVersion?: T;
  trigger?: T;
  startedAt?: T;
  endedAt?: T;
  cursor?: T;
  stats?: T;
  errors?:
    | T
    | {
        articleId?: T;
        message?: T;
        id?: T;
      };
  lockKey?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "suites_select".
 */
export interface SuitesSelect<T extends boolean = true> {
  site?: T;
  name?: T;
  slug?: T;
  tagline?: T;
  description?: T;
  shortDescription?: T;
  details?:
    | T
    | {
        bedrooms?: T;
        bathrooms?: T;
        maxGuests?: T;
        sqft?: T;
        floor?: T;
        hasPatio?: T;
        hasEnSuite?: T;
        isADACompliant?: T;
      };
  amenities?:
    | T
    | {
        name?: T;
        icon?: T;
        id?: T;
      };
  images?:
    | T
    | {
        image?: T;
        alt?: T;
        caption?: T;
        isPrimary?: T;
        id?: T;
      };
  lodgifyPropertyId?: T;
  pricing?:
    | T
    | {
        baseNightlyRate?: T;
        cleaningFee?: T;
        directBookingDiscount?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  status?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  site?: T;
  reviewerName?: T;
  reviewerLocation?: T;
  suite?: T;
  rating?: T;
  title?: T;
  content?: T;
  date?: T;
  highlights?:
    | T
    | {
        item?: T;
        id?: T;
      };
  source?: T;
  isFeatured?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "directory-entries_select".
 */
export interface DirectoryEntriesSelect<T extends boolean = true> {
  site?: T;
  name?: T;
  slug?: T;
  description?: T;
  shortDescription?: T;
  category?: T;
  subcategory?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  featuredImage?: T;
  logo?: T;
  location?:
    | T
    | {
        address?: T;
        city?: T;
        latitude?: T;
        longitude?: T;
        distanceFromProperty?: T;
        driveTimeMinutes?: T;
      };
  contact?:
    | T
    | {
        website?: T;
        phone?: T;
        email?: T;
      };
  details?:
    | T
    | {
        priceRange?: T;
        hours?: T;
        reservationRequired?: T;
        tastingFeeRange?: T;
        cuisineType?: T;
        capacity?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  isFeatured?: T;
  sortOrder?: T;
  status?: T;
  sourceUrl?: T;
  lastCrawledAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  site?: T;
  name?: T;
  slug?: T;
  description?: T;
  shortDescription?: T;
  featuredImage?: T;
  startDate?: T;
  endDate?: T;
  category?: T;
  location?:
    | T
    | {
        venueName?: T;
        address?: T;
        city?: T;
      };
  externalUrl?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  isFeatured?: T;
  status?: T;
  sourceUrl?: T;
  lastCrawledAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wineries_select".
 */
export interface WineriesSelect<T extends boolean = true> {
  site?: T;
  name?: T;
  slug?: T;
  website?: T;
  region?: T;
  subAppellation?: T;
  varietalFocus?:
    | T
    | {
        varietal?: T;
        id?: T;
      };
  tastingAvailable?: T;
  tastingBookingUrl?: T;
  wineClubEnabled?: T;
  featured?: T;
  featuredTier?: T;
  featuredOrder?: T;
  featuredHero?: T;
  featuredStory?: T;
  featuredQuote?: T;
  featuredQuoteAttribution?: T;
  phone?: T;
  email?: T;
  instagramHandle?: T;
  address?:
    | T
    | {
        street?: T;
        city?: T;
        state?: T;
        zip?: T;
      };
  coordinates?:
    | T
    | {
        lat?: T;
        lng?: T;
      };
  partnerSince?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wines_select".
 */
export interface WinesSelect<T extends boolean = true> {
  site?: T;
  name?: T;
  slug?: T;
  winery?: T;
  varietal?: T;
  vintage?: T;
  tastingNotes?: T;
  price?: T;
  priceTier?: T;
  rating?: T;
  purchaseUrl?: T;
  image?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "restaurants_select".
 */
export interface RestaurantsSelect<T extends boolean = true> {
  site?: T;
  name?: T;
  slug?: T;
  website?: T;
  region?: T;
  city?: T;
  cuisineType?:
    | T
    | {
        cuisine?: T;
        id?: T;
      };
  priceRange?: T;
  wineFocused?: T;
  reservationsUrl?: T;
  address?:
    | T
    | {
        street?: T;
        city?: T;
        state?: T;
        zip?: T;
      };
  phone?: T;
  hours?: T;
  featuredImage?: T;
  featured?: T;
  featuredTier?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accommodations_select".
 */
export interface AccommodationsSelect<T extends boolean = true> {
  site?: T;
  name?: T;
  slug?: T;
  website?: T;
  region?: T;
  city?: T;
  type?: T;
  priceRange?: T;
  bookingUrl?: T;
  address?:
    | T
    | {
        street?: T;
        city?: T;
        state?: T;
        zip?: T;
      };
  phone?: T;
  amenities?:
    | T
    | {
        amenity?: T;
        id?: T;
      };
  featuredImage?: T;
  featured?: T;
  featuredTier?: T;
  description?: T;
  isOwned?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "winery-events_select".
 */
export interface WineryEventsSelect<T extends boolean = true> {
  site?: T;
  title?: T;
  slug?: T;
  winery?: T;
  eventType?: T;
  startDate?: T;
  endDate?: T;
  price?: T;
  priceFree?: T;
  registrationUrl?: T;
  description?: T;
  featuredImage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}