/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    sites: Site;
    articles: Article;
    authors: Author;
    categories: Category;
    tags: Tag;
    support_kb_articles: SupportKbArticle;
    support_playbooks: SupportPlaybook;
    support_announcements: SupportAnnouncement;
    internal_link_rules: InternalLinkRule;
    internal_link_edges: InternalLinkEdge;
    internal_link_runs: InternalLinkRun;
    suites: Suite;
    reviews: Review;
    'directory-entries': DirectoryEntry;
    events: Event;
    wineries: Winery;
    wines: Wine;
    restaurants: Restaurant;
    accommodations: Accommodation;
    'winery-events': WineryEvent;
    specialists: Specialist;
    regions: Region;
    industries: Industry;
    vendors: Vendor;
    'vendor-certifications': VendorCertification;
    'vendor-facilities': VendorFacility;
    'vendor-services': VendorService;
    'commercial-relationships': CommercialRelationship;
    leads: Lead;
    series: Series;
    episodes: Episode;
    promos: Promo;
    templates: Template;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    sites: SitesSelect<false> | SitesSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    support_kb_articles: SupportKbArticlesSelect<false> | SupportKbArticlesSelect<true>;
    support_playbooks: SupportPlaybooksSelect<false> | SupportPlaybooksSelect<true>;
    support_announcements: SupportAnnouncementsSelect<false> | SupportAnnouncementsSelect<true>;
    internal_link_rules: InternalLinkRulesSelect<false> | InternalLinkRulesSelect<true>;
    internal_link_edges: InternalLinkEdgesSelect<false> | InternalLinkEdgesSelect<true>;
    internal_link_runs: InternalLinkRunsSelect<false> | InternalLinkRunsSelect<true>;
    suites: SuitesSelect<false> | SuitesSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    'directory-entries': DirectoryEntriesSelect<false> | DirectoryEntriesSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    wineries: WineriesSelect<false> | WineriesSelect<true>;
    wines: WinesSelect<false> | WinesSelect<true>;
    restaurants: RestaurantsSelect<false> | RestaurantsSelect<true>;
    accommodations: AccommodationsSelect<false> | AccommodationsSelect<true>;
    'winery-events': WineryEventsSelect<false> | WineryEventsSelect<true>;
    specialists: SpecialistsSelect<false> | SpecialistsSelect<true>;
    regions: RegionsSelect<false> | RegionsSelect<true>;
    industries: IndustriesSelect<false> | IndustriesSelect<true>;
    vendors: VendorsSelect<false> | VendorsSelect<true>;
    'vendor-certifications': VendorCertificationsSelect<false> | VendorCertificationsSelect<true>;
    'vendor-facilities': VendorFacilitiesSelect<false> | VendorFacilitiesSelect<true>;
    'vendor-services': VendorServicesSelect<false> | VendorServicesSelect<true>;
    'commercial-relationships': CommercialRelationshipsSelect<false> | CommercialRelationshipsSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    series: SeriesSelect<false> | SeriesSelect<true>;
    episodes: EpisodesSelect<false> | EpisodesSelect<true>;
    promos: PromosSelect<false> | PromosSelect<true>;
    templates: TemplatesSelect<false> | TemplatesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  site?: (number | null) | Site;
  alt: string;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sites".
 */
export interface Site {
  id: number;
  name: string;
  slug: string;
  /**
   * Domains that should resolve to this site (e.g. fightclubtech.com). Do NOT include protocol.
   */
  domains?:
    | {
        domain: string;
        id?: string | null;
      }[]
    | null;
  isDefault?: boolean | null;
  /**
   * Short brand tagline (e.g. "Find your direction.")
   */
  tagline?: string | null;
  /**
   * Site description for admin reference and SEO defaults
   */
  description?: string | null;
  /**
   * Primary site logo (SVG or PNG)
   */
  logo?: (number | null) | Media;
  /**
   * Site favicon (SVG or ICO)
   */
  favicon?: (number | null) | Media;
  /**
   * Primary brand color hex (e.g. #0F4C5C)
   */
  themeColor?: string | null;
  /**
   * Background color hex (e.g. #F4EDE0)
   */
  backgroundColor?: string | null;
  /**
   * Listmonk mailing list ID for newsletter signups on this site
   */
  listmonkListId?: string | null;
  /**
   * Mautic segment ID for this site
   */
  mauticSegmentId?: string | null;
  /**
   * Full URL for on-demand revalidation (e.g., https://resumecoach.me/api/revalidate). Leave empty to skip.
   */
  revalidateUrl?: string | null;
  /**
   * Secret token for the revalidation endpoint (passed as ?secret=...)
   */
  revalidateSecret?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  slug: string;
  /**
   * Short summary used on listing pages / previews.
   */
  excerpt?: string | null;
  /**
   * Main image for article cards and social sharing (recommended: 1200x630)
   */
  featuredImage?: (number | null) | Media;
  /**
   * Optional hero background image (full-width, can be same as featured)
   */
  heroImage?: (number | null) | Media;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Raw HTML from WordPress import. Rendered when Lexical content is not available.
   */
  html?: string | null;
  /**
   * First image extracted from imported HTML. Used for article cards.
   */
  thumbnailUrl?: string | null;
  categories?: (number | Category)[] | null;
  tags?: (number | Tag)[] | null;
  author?: (number | null) | Author;
  site: number | Site;
  /**
   * Article writing template (selected by BlogCraft or hand-set by editor).
   */
  template?: (number | null) | Template;
  /**
   * 3-5 bullets surfaced at the article top. Required for templated articles; optional for legacy.
   */
  top_takeaways?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * The article-level sources list. Replaces per-section bibliographic-theater sources blocks.
   */
  footer_sources?:
    | {
        title: string;
        publisher?: string | null;
        url: string;
        date?: string | null;
        quote_context?: string | null;
        id?: string | null;
      }[]
    | null;
  status: 'draft' | 'published';
  publishedAt?: string | null;
  /**
   * Date this article was last substantively reviewed for accuracy. Renders in the byline strip as "Last reviewed [date]" only when this date is populated AND differs from the published date. Leave blank if the article has not been reviewed since initial publication.
   */
  lastReviewed?: string | null;
  /**
   * Custom page <title> for search engines (50-60 chars). Falls back to title + site name.
   */
  metaTitle?: string | null;
  /**
   * Custom meta description for search results (150-160 chars). Falls back to excerpt.
   */
  metaDescription?: string | null;
  /**
   * Primary keyword this article targets. Used by SEO scoring and frontend optimization.
   */
  focusKeyword?: string | null;
  /**
   * Custom canonical URL if this article is syndicated or republished from another source.
   */
  canonicalUrl?: string | null;
  /**
   * Prevent search engines from indexing this article.
   */
  noIndex?: boolean | null;
  /**
   * Optional custom JSON-LD override. Leave empty to auto-generate Article schema.
   */
  structuredData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Latest SEO score (0–100).
   */
  seoScore?: number | null;
  seoGrade?: string | null;
  seoScoredAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  slug: string;
  url_segment: string;
  description?: string | null;
  sort_order?: number | null;
  /**
   * Lexi Explains only — accent color used for category cards and chips.
   */
  color?: ('green' | 'violet' | 'blue' | 'coral' | 'champagne') | null;
  /**
   * Lexi Explains only — custom SVG icon for this category.
   */
  icon?: (number | null) | Media;
  /**
   * Lexi Explains only — optional tagline shown on category landing pages.
   */
  tagline?: string | null;
  /**
   * Select parent category for hierarchy
   */
  parent?: (number | null) | Category;
  site: number | Site;
  breadcrumbs?:
    | {
        doc?: (number | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  name: string;
  slug: string;
  group:
    | 'industry'
    | 'persona'
    | 'regulation'
    | 'certification'
    | 'topic'
    | 'media'
    | 'method'
    | 'vendor-relationship'
    | 'diabetes-type'
    | 'audience'
    | 'format';
  description?: string | null;
  site: number | Site;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  name: string;
  slug: string;
  /**
   * Author role or title (e.g. "Lead Presenter", "Lived-Experience Presenter")
   */
  role?: string | null;
  /**
   * Contact email for this author persona (forwards to editorial team)
   */
  email?: string | null;
  bio?: string | null;
  avatar?: (number | null) | Media;
  /**
   * External image URL (e.g. from R2/Blogcraft). Used when no uploaded avatar is set.
   */
  avatarUrl?: string | null;
  website?: string | null;
  site: number | Site;
  isDefault?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * BlogCraft writing templates. Edits here sync automatically to api.blogcraft.app and from there into Neon. Do NOT edit templates directly in Neon — Payload is the source of truth.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "templates".
 */
export interface Template {
  id: number;
  /**
   * Template slug — must match BlogCraft’s prompt_key references. Example: pillar-comprehensive-guide. Locked after creation (see beforeChange hook).
   */
  slug: string;
  /**
   * Human-readable name, shown in admin UI dropdowns.
   */
  label: string;
  /**
   * High-level template family.
   */
  template_type: 'pillar' | 'spoke' | 'single_review' | 'vs_comparison' | 'roundup_review';
  /**
   * Specific article subtype. Examples: long_form_guide, listicle, how_to, explainer, buying_guide, product_review, service_review, product_comparison, alternatives_list, top_picks, best_of_roundup, supporting_article.
   */
  article_type: string;
  article_intent: 'informational' | 'commercial' | 'transactional';
  /**
   * Key referenced by BlogCraft’s prompt registry. Must match an existing entry in BlogCraft. Do not change without coordinating with BlogCraft prompt updates.
   */
  prompt_key: string;
  /**
   * Increment when changing required_sections or copy_primitives. Helps track template evolution.
   */
  outline_version: number;
  /**
   * Array of block primitives BlogCraft uses for this template. Example: ["authority_hook", "stat_proof", "expert_quote"]. Must be valid JSON array of strings.
   */
  copy_primitives:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Array of required article sections. Example: ["introduction", "table_of_contents", "what_is", "faq", "conclusion"]. Must be valid JSON array of strings.
   */
  required_sections:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Template configuration object. Includes tone, seo_notes, cta_placement, heading_depth, word_count_range, media_suggestions, internal_link_density, optional schema_markup and is_listicle.
   */
  template_json:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Active templates are eligible for BlogCraft to write to. Inactive templates remain in storage but won’t be selected for new articles.
   */
  is_active?: boolean | null;
  /**
   * True for templates that need structured data inputs (e.g. compared_products, roundup_items). BlogCraft validates against payload_schema before writing.
   */
  data_required?: boolean | null;
  /**
   * JSON Schema (draft-07) describing required data inputs when data_required is true. Used by BlogCraft to validate incoming research data.
   */
  payload_schema?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Human-readable message shown when data is missing. Example: “Product review templates require a review_subject with name + vendor + url + specs.”
   */
  data_required_message?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "support_kb_articles".
 */
export interface SupportKbArticle {
  id: number;
  /**
   * App identifier (e.g., "chat-widget", "dashboard")
   */
  appSlug: string;
  title: string;
  /**
   * Brief description shown in search results
   */
  summary?: string | null;
  /**
   * URL routes where this article is relevant
   */
  routes?:
    | {
        route: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Numbered steps (e.g., "1. Click Upload 2. Select file...")
   */
  stepsText?: string | null;
  /**
   * Keyword soup: synonyms, common phrasing, error messages
   */
  triggersText?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "support_playbooks".
 */
export interface SupportPlaybook {
  id: number;
  /**
   * App identifier (e.g., "chat-widget", "dashboard")
   */
  appSlug: string;
  title: string;
  /**
   * Brief description of what this playbook handles
   */
  summary?: string | null;
  /**
   * Priority level for this playbook
   */
  severity?: ('low' | 'medium' | 'high' | 'critical') | null;
  /**
   * URL routes where this playbook is relevant
   */
  routes?:
    | {
        route: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Keywords/phrases that trigger this playbook
   */
  triggers?:
    | {
        phrase: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Step-by-step instructions for handling this scenario
   */
  steps: {
    /**
     * Brief title for this step
     */
    stepTitle: string;
    /**
     * Detailed instructions for this step
     */
    stepBody: string;
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "support_announcements".
 */
export interface SupportAnnouncement {
  id: number;
  /**
   * App identifier (e.g., "chat-widget", "dashboard", or "*" for all)
   */
  appSlug: string;
  title: string;
  /**
   * The announcement message (shown in search results as summary)
   */
  message: string;
  /**
   * Severity level for visual styling
   */
  severity?: ('info' | 'warning' | 'critical') | null;
  /**
   * URL routes where this announcement should appear
   */
  routes?:
    | {
        route: string;
        id?: string | null;
      }[]
    | null;
  /**
   * When this announcement becomes active
   */
  startsAt?: string | null;
  /**
   * When this announcement should no longer appear
   */
  expiresAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "internal_link_rules".
 */
export interface InternalLinkRule {
  id: number;
  site: number | Site;
  targetArticle: number | Article;
  keywords: {
    keyword: string;
    id?: string | null;
  }[];
  priority?: number | null;
  maxLinksPerSource?: number | null;
  caseSensitive?: boolean | null;
  partialMatch?: boolean | null;
  enabled?: boolean | null;
  source: 'manual' | 'generated';
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "internal_link_edges".
 */
export interface InternalLinkEdge {
  id: number;
  site: number | Site;
  sourceArticle: number | Article;
  targetArticle: number | Article;
  keywordUsed?: string | null;
  anchorText?: string | null;
  contextHash: string;
  placement: 'in_body' | 'related_reading';
  targetUrl?: string | null;
  leftContext?: string | null;
  rightContext?: string | null;
  fingerprint?: string | null;
  status: 'active' | 'stale' | 'reverted';
  runId: number | InternalLinkRun;
  lastSeenRunId?: (number | null) | InternalLinkRun;
  revertRunId?: (number | null) | InternalLinkRun;
  updatedAt: string;
  createdAt: string;
}
/**
 * Run internal linker manually via endpoint: POST /api/internal-links/run?mode=dry_run|apply&site=all|<id>
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "internal_link_runs".
 */
export interface InternalLinkRun {
  id: number;
  site?: (number | null) | Site;
  mode: 'dry_run' | 'apply';
  status: 'queued' | 'running' | 'succeeded' | 'failed' | 'partial' | 'reverted';
  action: 'link' | 'revert';
  strategyVersion: string;
  trigger: 'manual' | 'scheduled' | 'endpoint';
  startedAt?: string | null;
  endedAt?: string | null;
  cursor?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  stats:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  errors?:
    | {
        articleId?: string | null;
        message: string;
        id?: string | null;
      }[]
    | null;
  lockKey: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "suites".
 */
export interface Suite {
  id: number;
  site: number | Site;
  name: string;
  slug: string;
  tagline: string;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  shortDescription?: string | null;
  details: {
    bedrooms: number;
    bathrooms: number;
    maxGuests: number;
    sqft?: number | null;
    floor?: ('ground' | 'upper') | null;
    hasPatio?: boolean | null;
    hasEnSuite?: boolean | null;
    isADACompliant?: boolean | null;
  };
  amenities?:
    | {
        name: string;
        icon?: string | null;
        id?: string | null;
      }[]
    | null;
  images?:
    | {
        image: number | Media;
        alt: string;
        caption?: string | null;
        isPrimary?: boolean | null;
        id?: string | null;
      }[]
    | null;
  lodgifyPropertyId: string;
  pricing?: {
    baseNightlyRate?: number | null;
    cleaningFee?: number | null;
    directBookingDiscount?: number | null;
  };
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  status?: ('active' | 'inactive') | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  site: number | Site;
  reviewerName: string;
  reviewerLocation?: string | null;
  suite: number | Suite;
  rating: number;
  title?: string | null;
  content: string;
  date: string;
  highlights?:
    | {
        item?: string | null;
        id?: string | null;
      }[]
    | null;
  source?: ('airbnb' | 'vrbo' | 'booking' | 'direct' | 'google') | null;
  isFeatured?: boolean | null;
  status?: ('active' | 'hidden') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "directory-entries".
 */
export interface DirectoryEntry {
  id: number;
  site: number | Site;
  /**
   * Determines content depth, schema, and conversion features. Promote based on GSC impression data or partnership status.
   */
  tier: 'tier-1' | 'tier-2' | 'tier-3';
  name: string;
  slug: string;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  shortDescription?: string | null;
  category: 'wineries' | 'restaurants' | 'activities' | 'venues' | 'lodging';
  subcategory?: string | null;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  featuredImage?: (number | null) | Media;
  logo?: (number | null) | Media;
  location?: {
    address?: string | null;
    city?: string | null;
    latitude?: number | null;
    longitude?: number | null;
    distanceFromProperty?: string | null;
    driveTimeMinutes?: number | null;
  };
  contact?: {
    website?: string | null;
    phone?: string | null;
    email?: string | null;
  };
  details?: {
    priceRange?: ('$' | '$$' | '$$$' | '$$$$') | null;
    hours?: string | null;
    reservationRequired?: boolean | null;
    tastingFeeRange?: string | null;
    cuisineType?: string | null;
    capacity?: string | null;
  };
  /**
   * Extended content sections required for Tier 2+ entries
   */
  extendedContent?: {
    whatMakesItSpecial?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    whoItsRightFor?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    whatToExpect?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    localContext?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    faqs?:
      | {
          question: string;
          answer: {
            root: {
              type: string;
              children: {
                type: any;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          };
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Photo gallery for Tier 2+ entries. 4-6 photos for Tier 2; 8-15 for Tier 3.
   */
  gallery?:
    | {
        image: number | Media;
        alt: string;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Winery-specific fields used for directory filtering and faceting
   */
  wineryDetails?: {
    ava?:
      | (
          | 'sonoma-valley'
          | 'russian-river-valley'
          | 'dry-creek-valley'
          | 'alexander-valley'
          | 'knights-valley'
          | 'bennett-valley'
          | 'chalk-hill'
          | 'rockpile'
          | 'sonoma-coast'
          | 'sonoma-mountain'
          | 'carneros-sonoma'
          | 'napa-valley'
          | 'stags-leap'
          | 'oakville'
          | 'rutherford'
          | 'st-helena'
          | 'calistoga'
          | 'mount-veeder'
          | 'howell-mountain'
          | 'spring-mountain'
          | 'atlas-peak'
          | 'diamond-mountain'
          | 'yountville'
          | 'oak-knoll'
          | 'wild-horse-valley'
          | 'carneros-napa'
          | 'coombsville'
        )
      | null;
    varietalsProduced?:
      | {
          varietal?: string | null;
          id?: string | null;
        }[]
      | null;
    wineryType?: ('boutique' | 'small-estate' | 'mid-size' | 'large') | null;
    familyOwned?: boolean | null;
    yearFounded?: number | null;
    reservationsRequired?: boolean | null;
    walkInsAccepted?: boolean | null;
    dogFriendly?: boolean | null;
    familyFriendly?: boolean | null;
    picnicFriendly?: boolean | null;
    walkingDistanceFromSonomaPlaza?: boolean | null;
  };
  /**
   * Commerce 7 integration tracking. The detection script auto-populates `enabled` and `detectedDomain`.
   */
  commerce7?: {
    enabled?: boolean | null;
    /**
     * Auto-populated by Commerce 7 detection script
     */
    detectedDomain?: string | null;
    detectedAt?: string | null;
    confidenceLevel?: ('high' | 'medium' | 'low') | null;
    partnershipStatus?: ('not-contacted' | 'outreach-sent' | 'in-conversation' | 'active' | 'declined') | null;
    /**
     * Commerce 7 shop widget embed code for Tier-3 partners
     */
    shopEmbedCode?: string | null;
    wineClubEmbedCode?: string | null;
    reservationEmbedCode?: string | null;
    partnerSince?: string | null;
    /**
     * Negotiated percentage (e.g., 20 for 20%). Internal use only.
     */
    revenueShareRate?: number | null;
  };
  /**
   * GSC and conversion data for tier promotion decisions. Auto-populated by sync job.
   */
  metrics?: {
    gscImpressions30d?: number | null;
    gscClicks30d?: number | null;
    gscAvgPosition?: number | null;
    lastSyncAt?: string | null;
  };
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
  };
  /**
   * Cluster articles that link to this directory entry. Bidirectional — update when articles are published.
   */
  relatedArticles?: (number | Article)[] | null;
  /**
   * Sister entries — nearby wineries, similar restaurants, etc. Surface as "You might also like" on Tier-2+ pages.
   */
  relatedDirectoryEntries?: (number | DirectoryEntry)[] | null;
  isFeatured?: boolean | null;
  sortOrder?: number | null;
  status?: ('published' | 'active' | 'inactive' | 'draft') | null;
  sourceUrl?: string | null;
  lastCrawledAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  site: number | Site;
  name: string;
  slug: string;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  shortDescription?: string | null;
  featuredImage?: (number | null) | Media;
  startDate: string;
  endDate?: string | null;
  category?: ('music' | 'wine-food' | 'arts-culture' | 'seasonal' | 'community' | 'festivals') | null;
  location?: {
    venueName?: string | null;
    address?: string | null;
    city?: string | null;
  };
  externalUrl?: string | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
  };
  isFeatured?: boolean | null;
  status?: ('active' | 'past') | null;
  sourceUrl?: string | null;
  lastCrawledAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wineries".
 */
export interface Winery {
  id: number;
  site: number | Site;
  name: string;
  slug: string;
  website?: string | null;
  region?: ('Napa Valley' | 'Sonoma County' | 'Coombsville AVA' | 'Stags Leap District' | 'Other') | null;
  subAppellation?: string | null;
  varietalFocus?:
    | {
        varietal?: string | null;
        id?: string | null;
      }[]
    | null;
  tastingAvailable?: boolean | null;
  tastingBookingUrl?: string | null;
  wineClubEnabled?: boolean | null;
  featured?: boolean | null;
  featuredTier?: ('flagship' | 'featured' | 'listed') | null;
  featuredOrder?: number | null;
  featuredHero?: (number | null) | Media;
  /**
   * Fallback hero image URL for wineries without an uploaded media object.
   */
  heroImageUrl?: string | null;
  featuredStory?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  featuredQuote?: string | null;
  featuredQuoteAttribution?: string | null;
  phone?: string | null;
  email?: string | null;
  instagramHandle?: string | null;
  address?: {
    street?: string | null;
    city?: string | null;
    state?: string | null;
    zip?: string | null;
  };
  coordinates?: {
    lat?: number | null;
    lng?: number | null;
  };
  partnerSince?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wines".
 */
export interface Wine {
  id: number;
  site: number | Site;
  name: string;
  slug: string;
  winery?: (number | null) | Winery;
  varietal?: string | null;
  vintage?: number | null;
  tastingNotes?: string | null;
  price?: number | null;
  priceTier?: ('under-50' | '50-100' | '100-200' | 'over-200') | null;
  rating?: number | null;
  purchaseUrl?: string | null;
  image?: (number | null) | Media;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "restaurants".
 */
export interface Restaurant {
  id: number;
  site: number | Site;
  name: string;
  slug: string;
  website?: string | null;
  region?: ('Napa Valley' | 'Sonoma County' | 'Other') | null;
  city?: string | null;
  cuisineType?:
    | {
        cuisine?: string | null;
        id?: string | null;
      }[]
    | null;
  priceRange?: ('$' | '$$' | '$$$' | '$$$$') | null;
  wineFocused?: boolean | null;
  reservationsUrl?: string | null;
  address?: {
    street?: string | null;
    city?: string | null;
    state?: string | null;
    zip?: string | null;
  };
  phone?: string | null;
  hours?: string | null;
  featuredImage?: (number | null) | Media;
  featured?: boolean | null;
  featuredTier?: ('flagship' | 'featured' | 'listed') | null;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accommodations".
 */
export interface Accommodation {
  id: number;
  site: number | Site;
  name: string;
  slug: string;
  website?: string | null;
  region?: ('Napa Valley' | 'Sonoma County' | 'Other') | null;
  city?: string | null;
  type?: ('hotel' | 'bb' | 'vacation-rental' | 'resort' | 'inn') | null;
  priceRange?: ('$' | '$$' | '$$$' | '$$$$') | null;
  bookingUrl?: string | null;
  address?: {
    street?: string | null;
    city?: string | null;
    state?: string | null;
    zip?: string | null;
  };
  phone?: string | null;
  amenities?:
    | {
        amenity?: string | null;
        id?: string | null;
      }[]
    | null;
  featuredImage?: (number | null) | Media;
  featured?: boolean | null;
  featuredTier?: ('flagship' | 'featured' | 'listed') | null;
  description?: string | null;
  /**
   * Check for Sonoma Grove Suites — appears first in listings.
   */
  isOwned?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "winery-events".
 */
export interface WineryEvent {
  id: number;
  site: number | Site;
  title: string;
  slug: string;
  winery?: (number | null) | Winery;
  eventType?: ('tasting' | 'dinner' | 'harvest' | 'release' | 'club' | 'other') | null;
  startDate: string;
  endDate?: string | null;
  price?: number | null;
  priceFree?: boolean | null;
  registrationUrl?: string | null;
  description?: string | null;
  featuredImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "specialists".
 */
export interface Specialist {
  id: number;
  site: number | Site;
  name: string;
  slug: string;
  type:
    | 'endocrinologist'
    | 'cdces'
    | 'diabetes-clinic'
    | 'primary-care-with-diabetes-focus'
    | 'pediatric-endocrinologist';
  /**
   * e.g. "MD, FACE" or "RN, CDCES" — displayed after name
   */
  credentials?: string | null;
  /**
   * National Provider Identifier (10 digits) — used for verification and dedup against NPI Registry
   */
  npi?: string | null;
  /**
   * Practice or clinic name for individual specialists with an affiliation
   */
  practiceName?: string | null;
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  yearsInPractice?: number | null;
  specialties?:
    | (
        | 'type-1-diabetes'
        | 'type-2-diabetes'
        | 'lada'
        | 'mody'
        | 'type-3c'
        | 'gestational'
        | 'pediatric'
        | 'geriatric'
        | 'insulin-pump-management'
        | 'cgm-management'
        | 'diabetic-neuropathy'
        | 'diabetic-retinopathy'
        | 'diabetic-kidney-disease'
        | 'weight-management-glp1'
      )[]
    | null;
  languagesSpoken?:
    | {
        language: string;
        id?: string | null;
      }[]
    | null;
  acceptingNewPatients?: boolean | null;
  telehealthAvailable?: boolean | null;
  location: {
    address1?: string | null;
    address2?: string | null;
    city: string;
    state: string;
    zipCode: string;
    latitude?: number | null;
    longitude?: number | null;
  };
  /**
   * Tag to metro, state, and/or broad region for directory filtering
   */
  regions?: (number | Region)[] | null;
  phone?: string | null;
  fax?: string | null;
  websiteUrl?: string | null;
  bookingUrl?: string | null;
  insuranceAccepted?:
    | {
        plan: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Headshot for individuals, building photo for clinics
   */
  photo?: (number | null) | Media;
  photoGallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  featured?: boolean | null;
  featuredTier?: ('flagship' | 'featured' | 'standard') | null;
  /**
   * Sort order within tier (lower = earlier)
   */
  featuredOrder?: number | null;
  /**
   * True once the specialist has verified and claimed their listing
   */
  claimedByOwner?: boolean | null;
  /**
   * When verified against NPI Registry or state board
   */
  verifiedDate?: string | null;
  /**
   * DiabetesCompass team notes on why this specialist is recommended (visible on flagship/featured listings only)
   */
  editorialNote?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Anonymized summary of patient feedback — manual editorial, not user-submitted reviews
   */
  patientReviewSummary?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  status: 'draft' | 'published' | 'archived';
  publishedAt?: string | null;
  dataSource?: ('npi-registry' | 'manual-entry' | 'claimed' | 'imported') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "regions".
 */
export interface Region {
  id: number;
  site: number | Site;
  name: string;
  slug: string;
  tier: 'state' | 'metro' | 'region';
  /**
   * 2-character US state code (e.g. AZ, CA). For state and metro tiers.
   */
  stateCode?: string | null;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industries".
 */
export interface Industry {
  id: number;
  display_name: string;
  slug: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vendors".
 */
export interface Vendor {
  id: number;
  name: string;
  slug: string;
  website?: string | null;
  description?: string | null;
  logo?: (number | null) | Media;
  hq_city?: string | null;
  hq_state?: string | null;
  hq_country?: string | null;
  phone?: string | null;
  email?: string | null;
  founded_year?: number | null;
  employee_count_range?: string | null;
  industries_served?: (number | Industry)[] | null;
  /**
   * Editorial assessment section. Owned and maintained by the editorial team (editor role only). The public profile renders the "Our Take" block only when summary_status is set to "Published". Draft and Needs Review content is never exposed to the frontend.
   */
  editorial?: {
    /**
     * Single-line descriptor written by editorial. Renders as the subhead under the vendor name on the profile page. NOT the vendor's tagline. Max 120 chars.
     */
    canonical_descriptor?: string | null;
    /**
     * 100–300 word factual editorial assessment in Marcus's voice. Comparative positioning, strengths, gaps, fit for buyer profile. See the editorial standards doc for register and constraints.
     */
    summary?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    /**
     * Controls whether the "Our Take" section renders on the public profile. Frontend renders the section only when status is "Published". Transition to Published also auto-sets Summary Last Reviewed to today's date.
     */
    summary_status?: ('draft' | 'published' | 'needs-review') | null;
    /**
     * Editorial team member who last reviewed and approved the summary. Should be set before transitioning status to "Published".
     */
    summary_reviewer?: (number | null) | User;
    /**
     * Auto-set to today when status transitions to "Published". Can be manually updated on re-review without changing status (e.g., after a factual accuracy check).
     */
    summary_last_reviewed?: string | null;
    /**
     * Optional editorial note about vertical-specific specialization (single paragraph). Renders as a trailing line below the Industries Served section on the public profile.
     */
    industry_notes?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  /**
   * Geographic coverage tiers. Select "Regional — specify states" to enable the Regional States field below for precise state/province listing.
   */
  coverage_area?:
    | ('northeast' | 'southeast' | 'midwest' | 'southwest' | 'west' | 'national' | 'global' | 'regional-specify')[]
    | null;
  /**
   * US states and Canadian provinces served. Activate by selecting "Regional — specify states" in Coverage Area above.
   */
  regional_states?:
    | {
        state_code:
          | 'AL'
          | 'AK'
          | 'AZ'
          | 'AR'
          | 'CA'
          | 'CO'
          | 'CT'
          | 'DE'
          | 'FL'
          | 'GA'
          | 'HI'
          | 'ID'
          | 'IL'
          | 'IN'
          | 'IA'
          | 'KS'
          | 'KY'
          | 'LA'
          | 'ME'
          | 'MD'
          | 'MA'
          | 'MI'
          | 'MN'
          | 'MS'
          | 'MO'
          | 'MT'
          | 'NE'
          | 'NV'
          | 'NH'
          | 'NJ'
          | 'NM'
          | 'NY'
          | 'NC'
          | 'ND'
          | 'OH'
          | 'OK'
          | 'OR'
          | 'PA'
          | 'RI'
          | 'SC'
          | 'SD'
          | 'TN'
          | 'TX'
          | 'UT'
          | 'VT'
          | 'VA'
          | 'WA'
          | 'WV'
          | 'WI'
          | 'WY'
          | 'DC'
          | 'AB'
          | 'BC'
          | 'MB'
          | 'NB'
          | 'NL'
          | 'NS'
          | 'ON'
          | 'PE'
          | 'QC'
          | 'SK';
        id?: string | null;
      }[]
    | null;
  /**
   * Notable clients. A client renders on the public profile only when "Publicly Disclosed" is checked AND a disclosure source URL is provided. Self-reported client lists without a verifiable source never appear publicly.
   */
  notable_clients?:
    | {
        /**
         * Client or organization name.
         */
        client_name: string;
        /**
         * Check only when the client relationship is confirmed by a public source (press release, case study, public contract, etc.). Do not check for self-reported client lists on vendor websites.
         */
        is_publicly_disclosed?: boolean | null;
        /**
         * URL of the public source confirming this client relationship. Required for the client to appear on the public profile. Leave blank for self-reported / unverified clients.
         */
        disclosure_source_url?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Auto-computed. True when one or more vendor-certification records for this vendor have verification_status = "verified". Updated automatically when certifications are saved or deleted. Do not edit manually.
   */
  has_verified_certifications?: boolean | null;
  is_published?: boolean | null;
  claim_status?: ('unclaimed' | 'pending-claim' | 'claimed') | null;
  provenance?: {
    primary_source_url?: string | null;
    crawled_at?: string | null;
    last_verified_at?: string | null;
    crawler_version?: string | null;
    verification_notes?: string | null;
  };
  /**
   * Public-facing data quality context. These flags render in the provenance footer on the profile page so readers understand why a profile has less information than others.
   */
  data_quality_flags?: {
    /**
     * Check when the vendor's public website provides minimal self-reported data (e.g., OEM ITAD arms with marketing-heavy pages). Triggers a footer notice explaining why this profile is thinner than others.
     */
    sparse_data?: boolean | null;
    /**
     * Check when the profile's last_verified_at is older than 90 days or when editorial is aware of pending vendor changes. Triggers a footer notice that the profile is pending review.
     */
    awaiting_re_verification?: boolean | null;
    /**
     * Check when the vendor's website uses aggressive bot protection that limited our automated crawl (e.g., Cloudflare challenges, Blue Star Recycling situation). Profile content is human-verified only. Triggers a footer notice that crawl was limited. Also surfaces as the is_bot_blocked transparency badge on the public profile.
     */
    bot_protection_limited_crawl?: boolean | null;
    /**
     * Optional editor-written note that appears in the footer when any of the above flags are true. Example: "This profile reflects publicly available information from the vendor's corporate website. Extended service details were not available on the pages crawled."
     */
    editor_note?: string | null;
  };
  /**
   * Set when this vendor is a known subsidiary of another ITAD company.
   */
  parent_company?: (number | null) | Vendor;
  /**
   * Populate once parent_company is set.
   */
  acquisition?: {
    acquired_date?: string | null;
    announcement_url?: string | null;
    subsidiary_status?: ('operating-as-brand' | 'merged-into-parent' | 'winding-down') | null;
    acquired_entity_notes?: string | null;
  };
  /**
   * For cases where the parent company is NOT in the Compare ITAD directory (e.g., a non-ITAD conglomerate parent like SK Group owning SK Tes). Use this instead of parent_company when the parent should not be a clickable directory link. If both fields are populated, parent_company (the relationship) takes precedence in the UI.
   */
  parent_company_text?: string | null;
  /**
   * Context for the parent_company_text relationship. Example: "SK Group is a South Korean industrial conglomerate; SK Tes is the ITAD operating unit following SK Ecoplant's acquisition of TES in 2022." This renders below the parent company name on the profile page.
   */
  parent_company_text_notes?: string | null;
  seo?: {
    meta_title?: string | null;
    meta_description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vendor-certifications".
 */
export interface VendorCertification {
  id: number;
  vendor: number | Vendor;
  certification_name: string;
  certification_body?: string | null;
  cert_number?: string | null;
  valid_from?: string | null;
  valid_through?: string | null;
  verification_status?: ('self-reported' | 'verified' | 'expired' | 'unverifiable') | null;
  verification_url?: string | null;
  verification_notes?: string | null;
  /**
   * Verbatim quote from the vendor's public source page where this certification is claimed. Required for new records (min 10 characters) to prevent hallucinated certifications. Capture the exact wording, not a paraphrase. The source URL goes in the verification_url field.
   */
  source_quote?: string | null;
  /**
   * Flagged for editorial review. Set automatically when source_quote is missing. Clear by adding a valid source_quote (10+ chars).
   */
  awaiting_re_verification?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vendor-facilities".
 */
export interface VendorFacility {
  id: number;
  vendor: number | Vendor;
  facility_name?: string | null;
  address?: string | null;
  city: string;
  state?: string | null;
  country?: string | null;
  postal_code?: string | null;
  lat?: number | null;
  lng?: number | null;
  ownership?: ('owned' | 'leased' | 'partner') | null;
  is_headquarters?: boolean | null;
  sq_footage?: number | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vendor-services".
 */
export interface VendorService {
  id: number;
  vendor: number | Vendor;
  service_type:
    | 'itad'
    | 'media-destruction'
    | 'data-wiping'
    | 'remarketing'
    | 'recycling'
    | 'refurbishment'
    | 'logistics'
    | 'leased-equipment-return'
    | 'itam'
    | 'cod'
    | 'on-site'
    | 'cloud-decommission'
    | 'other';
  description?: string | null;
  service_url?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Material commercial connections between Compare ITAD and listed vendors. Every active record renders in the /commercial-model transparency page. Add a record only when a real commercial relationship exists. Set is_active to false to remove from the public table without deleting the audit record.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "commercial-relationships".
 */
export interface CommercialRelationship {
  id: number;
  /**
   * The vendor with whom this commercial relationship exists. Must be an active listing in the Compare ITAD directory.
   */
  vendor: number | Vendor;
  /**
   * The nature of the commercial relationship. Renders verbatim in the Material Connections table on /commercial-model. Use the label that most accurately describes the actual arrangement.
   */
  connection_type: 'referral-partner' | 'premium-placement' | 'sponsored-content';
  /**
   * The date this commercial relationship took effect. Used for the "effective as of" column on the transparency table. Required.
   */
  effective_date: string;
  /**
   * Active relationships render on /commercial-model. Uncheck to remove from the public table without losing the audit record. The /commercial-model page queries where[is_active][equals]=true.
   */
  is_active?: boolean | null;
  /**
   * Internal editorial notes about this relationship. Never rendered publicly. Use to document contract references, review cadences, or escalation contacts.
   */
  internal_notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  first_name?: string | null;
  last_name?: string | null;
  email: string;
  phone?: string | null;
  company?: string | null;
  vendor?: (number | null) | Vendor;
  message?: string | null;
  source?: string | null;
  utm?: {
    source?: string | null;
    medium?: string | null;
    campaign?: string | null;
    term?: string | null;
    content?: string | null;
  };
  status?: ('new' | 'contacted' | 'qualified' | 'closed') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "series".
 */
export interface Series {
  id: number;
  title: string;
  slug: string;
  description?: string | null;
  category: number | Category;
  heroImage?: (number | null) | Media;
  /**
   * Planned total — episodes themselves are linked from the Episodes collection
   */
  totalEpisodes?: number | null;
  status?: ('active' | 'complete' | 'paused') | null;
  site: number | Site;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "episodes".
 */
export interface Episode {
  id: number;
  /**
   * Episode title — keep it punchy, e.g. "Credit Scores Are Like Dating".
   */
  title: string;
  slug: string;
  /**
   * Lexi’s opening line in the video — used as the meta description and excerpt.
   */
  hook?: string | null;
  category: number | Category;
  /**
   * Episode byline. Required — every episode has a host.
   */
  author: number | Author;
  /**
   * Optional — only set if this episode is part of a multi-part series.
   */
  series?: (number | null) | Series;
  /**
   * If part of a series, the episode number within the series.
   */
  episodeNumber?: number | null;
  videoSource: 'youtube' | 'tiktok' | 'direct';
  /**
   * YouTube video ID (the part after watch?v=).
   */
  youtubeId?: string | null;
  /**
   * Full TikTok video URL used as the embed source.
   */
  tiktokUrl?: string | null;
  directVideo?: (number | null) | Media;
  /**
   * Length in seconds.
   */
  duration?: number | null;
  /**
   * Vertical 9:16 still frame used as the thumbnail.
   */
  posterImage: number | Media;
  /**
   * Horizontal hero image for the article view (16:9 or similar).
   */
  heroImage?: (number | null) | Media;
  /**
   * Full transcript of what Lexi says — also great for SEO.
   */
  transcript?: string | null;
  /**
   * Optional longer-form companion article.
   */
  extendedContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * 3-5 bullet takeaways shown in the sidebar.
   */
  keyTakeaways?:
    | {
        point: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Public TikTok URL once posted.
   */
  tiktokPostUrl?: string | null;
  instagramUrl?: string | null;
  youtubeShortUrl?: string | null;
  /**
   * Manually update for tracking — optional.
   */
  tiktokViews?: number | null;
  metaTitle?: string | null;
  metaDescription?: string | null;
  ogImage?: (number | null) | Media;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Pin to homepage hero.
   */
  featured?: boolean | null;
  status: 'draft' | 'scheduled' | 'published' | 'archived';
  publishedAt?: string | null;
  site: number | Site;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promos".
 */
export interface Promo {
  id: number;
  name: string;
  product?: ('blogcraft' | 'resumecoach' | 'imagecrafter' | 'devmaestro' | 'mcpforge' | 'hisatech' | 'other') | null;
  headline: string;
  subhead?: string | null;
  ctaText: string;
  ctaUrl: string;
  image: number | Media;
  /**
   * Where this promo should appear. Multi-select.
   */
  placement?: ('home-banner' | 'sidebar-mid' | 'sidebar-bottom' | 'in-article' | 'newsletter-footer')[] | null;
  /**
   * Optional — show this promo only on episodes in these categories.
   */
  targetCategories?: (number | Category)[] | null;
  active?: boolean | null;
  startDate?: string | null;
  endDate?: string | null;
  site: number | Site;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'sites';
        value: number | Site;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'support_kb_articles';
        value: number | SupportKbArticle;
      } | null)
    | ({
        relationTo: 'support_playbooks';
        value: number | SupportPlaybook;
      } | null)
    | ({
        relationTo: 'support_announcements';
        value: number | SupportAnnouncement;
      } | null)
    | ({
        relationTo: 'internal_link_rules';
        value: number | InternalLinkRule;
      } | null)
    | ({
        relationTo: 'internal_link_edges';
        value: number | InternalLinkEdge;
      } | null)
    | ({
        relationTo: 'internal_link_runs';
        value: number | InternalLinkRun;
      } | null)
    | ({
        relationTo: 'suites';
        value: number | Suite;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'directory-entries';
        value: number | DirectoryEntry;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'wineries';
        value: number | Winery;
      } | null)
    | ({
        relationTo: 'wines';
        value: number | Wine;
      } | null)
    | ({
        relationTo: 'restaurants';
        value: number | Restaurant;
      } | null)
    | ({
        relationTo: 'accommodations';
        value: number | Accommodation;
      } | null)
    | ({
        relationTo: 'winery-events';
        value: number | WineryEvent;
      } | null)
    | ({
        relationTo: 'specialists';
        value: number | Specialist;
      } | null)
    | ({
        relationTo: 'regions';
        value: number | Region;
      } | null)
    | ({
        relationTo: 'industries';
        value: number | Industry;
      } | null)
    | ({
        relationTo: 'vendors';
        value: number | Vendor;
      } | null)
    | ({
        relationTo: 'vendor-certifications';
        value: number | VendorCertification;
      } | null)
    | ({
        relationTo: 'vendor-facilities';
        value: number | VendorFacility;
      } | null)
    | ({
        relationTo: 'vendor-services';
        value: number | VendorService;
      } | null)
    | ({
        relationTo: 'commercial-relationships';
        value: number | CommercialRelationship;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'series';
        value: number | Series;
      } | null)
    | ({
        relationTo: 'episodes';
        value: number | Episode;
      } | null)
    | ({
        relationTo: 'promos';
        value: number | Promo;
      } | null)
    | ({
        relationTo: 'templates';
        value: number | Template;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  site?: T;
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sites_select".
 */
export interface SitesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  domains?:
    | T
    | {
        domain?: T;
        id?: T;
      };
  isDefault?: T;
  tagline?: T;
  description?: T;
  logo?: T;
  favicon?: T;
  themeColor?: T;
  backgroundColor?: T;
  listmonkListId?: T;
  mauticSegmentId?: T;
  revalidateUrl?: T;
  revalidateSecret?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  featuredImage?: T;
  heroImage?: T;
  content?: T;
  html?: T;
  thumbnailUrl?: T;
  categories?: T;
  tags?: T;
  author?: T;
  site?: T;
  template?: T;
  top_takeaways?:
    | T
    | {
        text?: T;
        id?: T;
      };
  footer_sources?:
    | T
    | {
        title?: T;
        publisher?: T;
        url?: T;
        date?: T;
        quote_context?: T;
        id?: T;
      };
  status?: T;
  publishedAt?: T;
  lastReviewed?: T;
  metaTitle?: T;
  metaDescription?: T;
  focusKeyword?: T;
  canonicalUrl?: T;
  noIndex?: T;
  structuredData?: T;
  seoScore?: T;
  seoGrade?: T;
  seoScoredAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  role?: T;
  email?: T;
  bio?: T;
  avatar?: T;
  avatarUrl?: T;
  website?: T;
  site?: T;
  isDefault?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  url_segment?: T;
  description?: T;
  sort_order?: T;
  color?: T;
  icon?: T;
  tagline?: T;
  parent?: T;
  site?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  group?: T;
  description?: T;
  site?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "support_kb_articles_select".
 */
export interface SupportKbArticlesSelect<T extends boolean = true> {
  appSlug?: T;
  title?: T;
  summary?: T;
  routes?:
    | T
    | {
        route?: T;
        id?: T;
      };
  stepsText?: T;
  triggersText?: T;
  body?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "support_playbooks_select".
 */
export interface SupportPlaybooksSelect<T extends boolean = true> {
  appSlug?: T;
  title?: T;
  summary?: T;
  severity?: T;
  routes?:
    | T
    | {
        route?: T;
        id?: T;
      };
  triggers?:
    | T
    | {
        phrase?: T;
        id?: T;
      };
  steps?:
    | T
    | {
        stepTitle?: T;
        stepBody?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "support_announcements_select".
 */
export interface SupportAnnouncementsSelect<T extends boolean = true> {
  appSlug?: T;
  title?: T;
  message?: T;
  severity?: T;
  routes?:
    | T
    | {
        route?: T;
        id?: T;
      };
  startsAt?: T;
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "internal_link_rules_select".
 */
export interface InternalLinkRulesSelect<T extends boolean = true> {
  site?: T;
  targetArticle?: T;
  keywords?:
    | T
    | {
        keyword?: T;
        id?: T;
      };
  priority?: T;
  maxLinksPerSource?: T;
  caseSensitive?: T;
  partialMatch?: T;
  enabled?: T;
  source?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "internal_link_edges_select".
 */
export interface InternalLinkEdgesSelect<T extends boolean = true> {
  site?: T;
  sourceArticle?: T;
  targetArticle?: T;
  keywordUsed?: T;
  anchorText?: T;
  contextHash?: T;
  placement?: T;
  targetUrl?: T;
  leftContext?: T;
  rightContext?: T;
  fingerprint?: T;
  status?: T;
  runId?: T;
  lastSeenRunId?: T;
  revertRunId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "internal_link_runs_select".
 */
export interface InternalLinkRunsSelect<T extends boolean = true> {
  site?: T;
  mode?: T;
  status?: T;
  action?: T;
  strategyVersion?: T;
  trigger?: T;
  startedAt?: T;
  endedAt?: T;
  cursor?: T;
  stats?: T;
  errors?:
    | T
    | {
        articleId?: T;
        message?: T;
        id?: T;
      };
  lockKey?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "suites_select".
 */
export interface SuitesSelect<T extends boolean = true> {
  site?: T;
  name?: T;
  slug?: T;
  tagline?: T;
  description?: T;
  shortDescription?: T;
  details?:
    | T
    | {
        bedrooms?: T;
        bathrooms?: T;
        maxGuests?: T;
        sqft?: T;
        floor?: T;
        hasPatio?: T;
        hasEnSuite?: T;
        isADACompliant?: T;
      };
  amenities?:
    | T
    | {
        name?: T;
        icon?: T;
        id?: T;
      };
  images?:
    | T
    | {
        image?: T;
        alt?: T;
        caption?: T;
        isPrimary?: T;
        id?: T;
      };
  lodgifyPropertyId?: T;
  pricing?:
    | T
    | {
        baseNightlyRate?: T;
        cleaningFee?: T;
        directBookingDiscount?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  status?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  site?: T;
  reviewerName?: T;
  reviewerLocation?: T;
  suite?: T;
  rating?: T;
  title?: T;
  content?: T;
  date?: T;
  highlights?:
    | T
    | {
        item?: T;
        id?: T;
      };
  source?: T;
  isFeatured?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "directory-entries_select".
 */
export interface DirectoryEntriesSelect<T extends boolean = true> {
  site?: T;
  tier?: T;
  name?: T;
  slug?: T;
  description?: T;
  shortDescription?: T;
  category?: T;
  subcategory?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  featuredImage?: T;
  logo?: T;
  location?:
    | T
    | {
        address?: T;
        city?: T;
        latitude?: T;
        longitude?: T;
        distanceFromProperty?: T;
        driveTimeMinutes?: T;
      };
  contact?:
    | T
    | {
        website?: T;
        phone?: T;
        email?: T;
      };
  details?:
    | T
    | {
        priceRange?: T;
        hours?: T;
        reservationRequired?: T;
        tastingFeeRange?: T;
        cuisineType?: T;
        capacity?: T;
      };
  extendedContent?:
    | T
    | {
        whatMakesItSpecial?: T;
        whoItsRightFor?: T;
        whatToExpect?: T;
        localContext?: T;
        faqs?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
      };
  gallery?:
    | T
    | {
        image?: T;
        alt?: T;
        caption?: T;
        id?: T;
      };
  wineryDetails?:
    | T
    | {
        ava?: T;
        varietalsProduced?:
          | T
          | {
              varietal?: T;
              id?: T;
            };
        wineryType?: T;
        familyOwned?: T;
        yearFounded?: T;
        reservationsRequired?: T;
        walkInsAccepted?: T;
        dogFriendly?: T;
        familyFriendly?: T;
        picnicFriendly?: T;
        walkingDistanceFromSonomaPlaza?: T;
      };
  commerce7?:
    | T
    | {
        enabled?: T;
        detectedDomain?: T;
        detectedAt?: T;
        confidenceLevel?: T;
        partnershipStatus?: T;
        shopEmbedCode?: T;
        wineClubEmbedCode?: T;
        reservationEmbedCode?: T;
        partnerSince?: T;
        revenueShareRate?: T;
      };
  metrics?:
    | T
    | {
        gscImpressions30d?: T;
        gscClicks30d?: T;
        gscAvgPosition?: T;
        lastSyncAt?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  relatedArticles?: T;
  relatedDirectoryEntries?: T;
  isFeatured?: T;
  sortOrder?: T;
  status?: T;
  sourceUrl?: T;
  lastCrawledAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  site?: T;
  name?: T;
  slug?: T;
  description?: T;
  shortDescription?: T;
  featuredImage?: T;
  startDate?: T;
  endDate?: T;
  category?: T;
  location?:
    | T
    | {
        venueName?: T;
        address?: T;
        city?: T;
      };
  externalUrl?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  isFeatured?: T;
  status?: T;
  sourceUrl?: T;
  lastCrawledAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wineries_select".
 */
export interface WineriesSelect<T extends boolean = true> {
  site?: T;
  name?: T;
  slug?: T;
  website?: T;
  region?: T;
  subAppellation?: T;
  varietalFocus?:
    | T
    | {
        varietal?: T;
        id?: T;
      };
  tastingAvailable?: T;
  tastingBookingUrl?: T;
  wineClubEnabled?: T;
  featured?: T;
  featuredTier?: T;
  featuredOrder?: T;
  featuredHero?: T;
  heroImageUrl?: T;
  featuredStory?: T;
  featuredQuote?: T;
  featuredQuoteAttribution?: T;
  phone?: T;
  email?: T;
  instagramHandle?: T;
  address?:
    | T
    | {
        street?: T;
        city?: T;
        state?: T;
        zip?: T;
      };
  coordinates?:
    | T
    | {
        lat?: T;
        lng?: T;
      };
  partnerSince?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wines_select".
 */
export interface WinesSelect<T extends boolean = true> {
  site?: T;
  name?: T;
  slug?: T;
  winery?: T;
  varietal?: T;
  vintage?: T;
  tastingNotes?: T;
  price?: T;
  priceTier?: T;
  rating?: T;
  purchaseUrl?: T;
  image?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "restaurants_select".
 */
export interface RestaurantsSelect<T extends boolean = true> {
  site?: T;
  name?: T;
  slug?: T;
  website?: T;
  region?: T;
  city?: T;
  cuisineType?:
    | T
    | {
        cuisine?: T;
        id?: T;
      };
  priceRange?: T;
  wineFocused?: T;
  reservationsUrl?: T;
  address?:
    | T
    | {
        street?: T;
        city?: T;
        state?: T;
        zip?: T;
      };
  phone?: T;
  hours?: T;
  featuredImage?: T;
  featured?: T;
  featuredTier?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accommodations_select".
 */
export interface AccommodationsSelect<T extends boolean = true> {
  site?: T;
  name?: T;
  slug?: T;
  website?: T;
  region?: T;
  city?: T;
  type?: T;
  priceRange?: T;
  bookingUrl?: T;
  address?:
    | T
    | {
        street?: T;
        city?: T;
        state?: T;
        zip?: T;
      };
  phone?: T;
  amenities?:
    | T
    | {
        amenity?: T;
        id?: T;
      };
  featuredImage?: T;
  featured?: T;
  featuredTier?: T;
  description?: T;
  isOwned?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "winery-events_select".
 */
export interface WineryEventsSelect<T extends boolean = true> {
  site?: T;
  title?: T;
  slug?: T;
  winery?: T;
  eventType?: T;
  startDate?: T;
  endDate?: T;
  price?: T;
  priceFree?: T;
  registrationUrl?: T;
  description?: T;
  featuredImage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "specialists_select".
 */
export interface SpecialistsSelect<T extends boolean = true> {
  site?: T;
  name?: T;
  slug?: T;
  type?: T;
  credentials?: T;
  npi?: T;
  practiceName?: T;
  bio?: T;
  yearsInPractice?: T;
  specialties?: T;
  languagesSpoken?:
    | T
    | {
        language?: T;
        id?: T;
      };
  acceptingNewPatients?: T;
  telehealthAvailable?: T;
  location?:
    | T
    | {
        address1?: T;
        address2?: T;
        city?: T;
        state?: T;
        zipCode?: T;
        latitude?: T;
        longitude?: T;
      };
  regions?: T;
  phone?: T;
  fax?: T;
  websiteUrl?: T;
  bookingUrl?: T;
  insuranceAccepted?:
    | T
    | {
        plan?: T;
        id?: T;
      };
  photo?: T;
  photoGallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  featured?: T;
  featuredTier?: T;
  featuredOrder?: T;
  claimedByOwner?: T;
  verifiedDate?: T;
  editorialNote?: T;
  patientReviewSummary?: T;
  status?: T;
  publishedAt?: T;
  dataSource?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "regions_select".
 */
export interface RegionsSelect<T extends boolean = true> {
  site?: T;
  name?: T;
  slug?: T;
  tier?: T;
  stateCode?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industries_select".
 */
export interface IndustriesSelect<T extends boolean = true> {
  display_name?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vendors_select".
 */
export interface VendorsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  website?: T;
  description?: T;
  logo?: T;
  hq_city?: T;
  hq_state?: T;
  hq_country?: T;
  phone?: T;
  email?: T;
  founded_year?: T;
  employee_count_range?: T;
  industries_served?: T;
  editorial?:
    | T
    | {
        canonical_descriptor?: T;
        summary?: T;
        summary_status?: T;
        summary_reviewer?: T;
        summary_last_reviewed?: T;
        industry_notes?: T;
      };
  coverage_area?: T;
  regional_states?:
    | T
    | {
        state_code?: T;
        id?: T;
      };
  notable_clients?:
    | T
    | {
        client_name?: T;
        is_publicly_disclosed?: T;
        disclosure_source_url?: T;
        id?: T;
      };
  has_verified_certifications?: T;
  is_published?: T;
  claim_status?: T;
  provenance?:
    | T
    | {
        primary_source_url?: T;
        crawled_at?: T;
        last_verified_at?: T;
        crawler_version?: T;
        verification_notes?: T;
      };
  data_quality_flags?:
    | T
    | {
        sparse_data?: T;
        awaiting_re_verification?: T;
        bot_protection_limited_crawl?: T;
        editor_note?: T;
      };
  parent_company?: T;
  acquisition?:
    | T
    | {
        acquired_date?: T;
        announcement_url?: T;
        subsidiary_status?: T;
        acquired_entity_notes?: T;
      };
  parent_company_text?: T;
  parent_company_text_notes?: T;
  seo?:
    | T
    | {
        meta_title?: T;
        meta_description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vendor-certifications_select".
 */
export interface VendorCertificationsSelect<T extends boolean = true> {
  vendor?: T;
  certification_name?: T;
  certification_body?: T;
  cert_number?: T;
  valid_from?: T;
  valid_through?: T;
  verification_status?: T;
  verification_url?: T;
  verification_notes?: T;
  source_quote?: T;
  awaiting_re_verification?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vendor-facilities_select".
 */
export interface VendorFacilitiesSelect<T extends boolean = true> {
  vendor?: T;
  facility_name?: T;
  address?: T;
  city?: T;
  state?: T;
  country?: T;
  postal_code?: T;
  lat?: T;
  lng?: T;
  ownership?: T;
  is_headquarters?: T;
  sq_footage?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vendor-services_select".
 */
export interface VendorServicesSelect<T extends boolean = true> {
  vendor?: T;
  service_type?: T;
  description?: T;
  service_url?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "commercial-relationships_select".
 */
export interface CommercialRelationshipsSelect<T extends boolean = true> {
  vendor?: T;
  connection_type?: T;
  effective_date?: T;
  is_active?: T;
  internal_notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  first_name?: T;
  last_name?: T;
  email?: T;
  phone?: T;
  company?: T;
  vendor?: T;
  message?: T;
  source?: T;
  utm?:
    | T
    | {
        source?: T;
        medium?: T;
        campaign?: T;
        term?: T;
        content?: T;
      };
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "series_select".
 */
export interface SeriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  category?: T;
  heroImage?: T;
  totalEpisodes?: T;
  status?: T;
  site?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "episodes_select".
 */
export interface EpisodesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  hook?: T;
  category?: T;
  author?: T;
  series?: T;
  episodeNumber?: T;
  videoSource?: T;
  youtubeId?: T;
  tiktokUrl?: T;
  directVideo?: T;
  duration?: T;
  posterImage?: T;
  heroImage?: T;
  transcript?: T;
  extendedContent?: T;
  keyTakeaways?:
    | T
    | {
        point?: T;
        id?: T;
      };
  tiktokPostUrl?: T;
  instagramUrl?: T;
  youtubeShortUrl?: T;
  tiktokViews?: T;
  metaTitle?: T;
  metaDescription?: T;
  ogImage?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  featured?: T;
  status?: T;
  publishedAt?: T;
  site?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promos_select".
 */
export interface PromosSelect<T extends boolean = true> {
  name?: T;
  product?: T;
  headline?: T;
  subhead?: T;
  ctaText?: T;
  ctaUrl?: T;
  image?: T;
  placement?: T;
  targetCategories?: T;
  active?: T;
  startDate?: T;
  endDate?: T;
  site?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "templates_select".
 */
export interface TemplatesSelect<T extends boolean = true> {
  slug?: T;
  label?: T;
  template_type?: T;
  article_type?: T;
  article_intent?: T;
  prompt_key?: T;
  outline_version?: T;
  copy_primitives?: T;
  required_sections?: T;
  template_json?: T;
  is_active?: T;
  data_required?: T;
  payload_schema?: T;
  data_required_message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}